// Activities are where side effects live: network calls, payments, inventory
// mutations. Temporal records each activity's result in workflow history, so
// a completed step is never re-executed on replay — only unfinished work is
// retried. Every external system here is mocked as a plain async function;
// in production each would be a real API client.
import { ApplicationFailure, Context } from '@temporalio/activity';
import type { Order } from './shared';

// Simulated service latency (mock stand-in for real network/API time).
// A plain setTimeout is fine HERE because activities are allowed to be slow,
// non-deterministic, and side-effectful — that's exactly why this lives in an
// activity and not in workflow code, which must replay deterministically.
const serviceLatency = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

// Money formatting for the demo narrative — logs should read like a business
// event stream, not a stack trace.
const usd = (amount: number) => `$${amount.toFixed(2)}`;
const skus = (order: Order) =>
  order.items.map((i) => `${i.quantity}x ${i.sku}`).join(', ');

// The idempotency key is generated by the WORKFLOW (deterministic, stable
// across retries and replays) and merely used here. A real payment gateway
// would dedupe on it server-side, so a retried call can never double-charge.
export async function authorizePayment(order: Order, idempotencyKey: string): Promise<string> {
  await serviceLatency(350);
  const authId = `auth-${order.id}`;

  console.log(
    `[payment] authorized ${usd(order.amount)} for order ${order.id} ` +
    `(auth ${authId}, idempotency key ${idempotencyKey}) — funds held, not yet charged`,
  );
  return authId;
}

export async function reserveInventory(order: Order): Promise<string> {
  // Transient-failure injection: fail the first two attempts, succeed on the
  // third. We read the attempt number from Temporal itself (it's tracked
  // server-side), so this needs no shared state and still behaves correctly
  // if the worker is killed and restarted mid-retry. A thrown Error is
  // retryable by default — the workflow code never sees the first two
  // failures, the retry policy absorbs them.
  await serviceLatency(200);

  const { attempt } = Context.current().info;

  if (order.simulate === 'flaky-inventory' && attempt <= 2) {
    console.log(
      `[inventory] attempt ${attempt}: warehouse service timed out for order ${order.id} — ` +
      `Temporal will retry automatically`,
    );
    await serviceLatency(500);
    throw new Error(`warehouse service timeout (attempt ${attempt})`);
  }

  const reservationId = `resv-${order.id}`;

  console.log(
    `[inventory] reserved ${skus(order)} for order ${order.id} (reservation ${reservationId})`,
  );
  return reservationId;
}

export async function createShipment(order: Order): Promise<string> {
  await serviceLatency(450);
  // Permanent-failure injection: the carrier rejects this order outright
  // (think: unserviceable address). Unlike the transient inventory timeout,
  // retrying cannot fix a business-rule rejection — so we throw a
  // NON-RETRYABLE ApplicationFailure. That skips the retry policy entirely
  // and fails the activity on attempt 1, which is what hands control to the
  // workflow's compensation path immediately instead of after minutes of
  // pointless retries.
  if (order.simulate === 'shipment-failure') {
    console.log(
      `[shipping] carrier REJECTED order ${order.id}: destination address unserviceable — permanent, retrying will not help`,
    );

    // Throw a non-retryable application failure to simulate a permanent failure
    throw ApplicationFailure.create({
      nonRetryable: true,
      type: 'ShipmentError',
      message: `carrier rejected shipment for order ${order.id}: address unserviceable`,
    });
  }

  const trackingId = `track-${order.id}`;
  console.log(
    `[shipping] shipment created for order ${order.id}, tracking ${trackingId}`,
  );
  return trackingId;
}

export async function capturePayment(order: Order, authId: string, idempotencyKey: string): Promise<void> {
  await serviceLatency(300);
  console.log(
    `[payment] captured ${usd(order.amount)} on ${authId} for order ${order.id} ` +
    `(idempotency key ${idempotencyKey}) — customer charged exactly once`,
  );
}

export async function sendConfirmation(order: Order): Promise<void> {
  await serviceLatency(150);
  console.log(
    `[notification] confirmation sent for order ${order.id} — customer knows their order is on the way`,
  );
}

// ---------------------------------------------------------------------------
// Compensations (saga undo steps). Each reverses one successful forward step.
// They get the same production care as forward steps for free: the activity
// retry policy applies to them too, and they're idempotent by design — keyed
// on stable ids (reservationId, authId), so running one twice is harmless.
// ---------------------------------------------------------------------------

export async function voidPaymentAuthorization(order: Order, authId: string): Promise<void> {
  await serviceLatency(300);
  console.log(
    `[payment] voided authorization ${authId} for ${usd(order.amount)} — customer was never charged`,
  );
}

export async function releaseInventory(order: Order, reservationId: string): Promise<void> {
  await serviceLatency(200);
  console.log(
    `[inventory] released reservation ${reservationId} (${skus(order)}) — stock available for other orders again`,
  );
}

export async function cancelShipment(order: Order, trackingId: string): Promise<void> {
  await serviceLatency(250);
  console.log(
    `[shipping] cancelled shipment ${trackingId} for order ${order.id} — carrier will not dispatch, package recalled`,
  );
}

export async function refundPayment(order: Order, authId: string, idempotencyKey: string): Promise<void> {
  // A refund, not a void: the money already MOVED at capture, so we return it
  // rather than release a hold. Keyed on its own idempotency key so a retried
  // refund can never pay the customer back twice.
  await serviceLatency(100);
  console.log(
    `[payment] refunded ${usd(order.amount)} on ${authId} for order ${order.id} ` +
    `(idempotency key ${idempotencyKey}) — customer made whole after a captured charge`,
  );
}
